import os
import datetime


# print(dir(os))
# os.getcwd()
# result = os.stat("iterators.py")
# x = datetime.datetime.fromtimestamp(result.st_atime)
# print(x)

# result = os.access()
# print(dir(os))

# mevcut = os.getcwd()
# result =os.chdir('C:\\Users\\ibrahim Ethem\\OneDrive\\Masaüstü')
# # file = os.startfile(os.curdir)
# # print(os.listdir(mevcut))
# os.rename("BAP 1. rapot örnek 1.docx","Bap rapor cevap.docx")

dizin = os.getcwd()

# def tara(dizin):
#     başlangıç = os.getcwd()
#     dosyalar = []
#     os.chdir(dizin)

#     for öğe in os.listdir(os.curdir):
#         if not os.path.isdir(öğe):
#             dosyalar.append(öğe)
#         else:
#             dosyalar.extend(tara(öğe))

#     os.chdir(başlangıç)
#     return dosyalar
# print(dizin)
# for kökdizin, altdizinler, dosyalar in os.walk('anadizin'):
#     for dosya in dosyalar:
#             if dosya.endswith('.jpeg'):
#                     print(dosya)

# print(result)

os.system("spotify.exe")
